#!/bin/sh

cat << EOF > /etc/nginx/fastcgi.env
fastcgi_param APP_MYSQL_HOST $APP_MYSQL_HOST;
fastcgi_param APP_MYSQL_NAME $APP_MYSQL_NAME;
fastcgi_param APP_MYSQL_USER $APP_MYSQL_USER;
fastcgi_param APP_MYSQL_PASS $APP_MYSQL_PASS;
fastcgi_param APP_MYSQL_PORT $APP_MYSQL_PORT;
EOF

exec "supervisord" "-c" "/etc/supervisor.conf"
